server:
  port: 8090
  servlet:
    context-path: '/form_designer'

spring:
  data:
    mongodb:
      uri: mongodb://db_kangyu:db_kangyu_11@10.10.10.51:27017/test?authSource=db_kangyu&authMechanism=SCRAM-SHA-1